package com.troytan.notify.domain;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_comment.COMMENT_ID
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_comment.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_comment.NOTIFY_ID
     *
     * @mbg.generated
     */
    private Integer notifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_comment.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_comment.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_comment.COMMENT_ID
     *
     * @return the value of tt_comment.COMMENT_ID
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_comment.COMMENT_ID
     *
     * @param commentId the value for tt_comment.COMMENT_ID
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_comment.CONTENT
     *
     * @return the value of tt_comment.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_comment.CONTENT
     *
     * @param content the value for tt_comment.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_comment.NOTIFY_ID
     *
     * @return the value of tt_comment.NOTIFY_ID
     *
     * @mbg.generated
     */
    public Integer getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_comment.NOTIFY_ID
     *
     * @param notifyId the value for tt_comment.NOTIFY_ID
     *
     * @mbg.generated
     */
    public void setNotifyId(Integer notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_comment.CREATE_BY
     *
     * @return the value of tt_comment.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_comment.CREATE_BY
     *
     * @param createBy the value for tt_comment.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_comment.CREATE_ON
     *
     * @return the value of tt_comment.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_comment.CREATE_ON
     *
     * @param createOn the value for tt_comment.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }
}