package com.troytan.notify.domain;

import java.util.Date;

public class Confirm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_confirm.CONFIRM_ID
     *
     * @mbg.generated
     */
    private Integer confirmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_confirm.STATUS
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_confirm.NOTIFY_ID
     *
     * @mbg.generated
     */
    private Integer notifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_confirm.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_confirm.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_confirm.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_confirm.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_confirm.CONFIRM_ID
     *
     * @return the value of tt_confirm.CONFIRM_ID
     *
     * @mbg.generated
     */
    public Integer getConfirmId() {
        return confirmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_confirm.CONFIRM_ID
     *
     * @param confirmId the value for tt_confirm.CONFIRM_ID
     *
     * @mbg.generated
     */
    public void setConfirmId(Integer confirmId) {
        this.confirmId = confirmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_confirm.STATUS
     *
     * @return the value of tt_confirm.STATUS
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_confirm.STATUS
     *
     * @param status the value for tt_confirm.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_confirm.NOTIFY_ID
     *
     * @return the value of tt_confirm.NOTIFY_ID
     *
     * @mbg.generated
     */
    public Integer getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_confirm.NOTIFY_ID
     *
     * @param notifyId the value for tt_confirm.NOTIFY_ID
     *
     * @mbg.generated
     */
    public void setNotifyId(Integer notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_confirm.CREATE_BY
     *
     * @return the value of tt_confirm.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_confirm.CREATE_BY
     *
     * @param createBy the value for tt_confirm.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_confirm.CREATE_ON
     *
     * @return the value of tt_confirm.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_confirm.CREATE_ON
     *
     * @param createOn the value for tt_confirm.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_confirm.UPDATE_BY
     *
     * @return the value of tt_confirm.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_confirm.UPDATE_BY
     *
     * @param updateBy the value for tt_confirm.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_confirm.UPDATE_ON
     *
     * @return the value of tt_confirm.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_confirm.UPDATE_ON
     *
     * @param updateOn the value for tt_confirm.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }
}