package com.troytan.notify.domain;

import java.util.Date;

public class Designer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.DESIGNER_ID
     *
     * @mbg.generated
     */
    private Integer designerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.ORDER_NUM
     *
     * @mbg.generated
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.PHOTO
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.PHOTO_DETAIL
     *
     * @mbg.generated
     */
    private String photoDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_designer.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.DESIGNER_ID
     *
     * @return the value of tt_designer.DESIGNER_ID
     *
     * @mbg.generated
     */
    public Integer getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.DESIGNER_ID
     *
     * @param designerId the value for tt_designer.DESIGNER_ID
     *
     * @mbg.generated
     */
    public void setDesignerId(Integer designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.NAME
     *
     * @return the value of tt_designer.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.NAME
     *
     * @param name the value for tt_designer.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.ORDER_NUM
     *
     * @return the value of tt_designer.ORDER_NUM
     *
     * @mbg.generated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.ORDER_NUM
     *
     * @param orderNum the value for tt_designer.ORDER_NUM
     *
     * @mbg.generated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.PHOTO
     *
     * @return the value of tt_designer.PHOTO
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.PHOTO
     *
     * @param photo the value for tt_designer.PHOTO
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.DESCRIPTION
     *
     * @return the value of tt_designer.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.DESCRIPTION
     *
     * @param description the value for tt_designer.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.PHOTO_DETAIL
     *
     * @return the value of tt_designer.PHOTO_DETAIL
     *
     * @mbg.generated
     */
    public String getPhotoDetail() {
        return photoDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.PHOTO_DETAIL
     *
     * @param photoDetail the value for tt_designer.PHOTO_DETAIL
     *
     * @mbg.generated
     */
    public void setPhotoDetail(String photoDetail) {
        this.photoDetail = photoDetail == null ? null : photoDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.CREATE_ON
     *
     * @return the value of tt_designer.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.CREATE_ON
     *
     * @param createOn the value for tt_designer.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.CREATE_BY
     *
     * @return the value of tt_designer.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.CREATE_BY
     *
     * @param createBy the value for tt_designer.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.UPDATE_ON
     *
     * @return the value of tt_designer.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.UPDATE_ON
     *
     * @param updateOn the value for tt_designer.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_designer.UPDATE_BY
     *
     * @return the value of tt_designer.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_designer.UPDATE_BY
     *
     * @param updateBy the value for tt_designer.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}