package com.troytan.notify.domain;

public class FitmentDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_fitment_detail.FITMENT_DETAIL_ID
     *
     * @mbg.generated
     */
    private Integer fitmentDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_fitment_detail.IMG_URL
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_fitment_detail.FITMENT_ID
     *
     * @mbg.generated
     */
    private Long fitmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_fitment_detail.FITMENT_DETAIL_ID
     *
     * @return the value of tt_fitment_detail.FITMENT_DETAIL_ID
     *
     * @mbg.generated
     */
    public Integer getFitmentDetailId() {
        return fitmentDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_fitment_detail.FITMENT_DETAIL_ID
     *
     * @param fitmentDetailId the value for tt_fitment_detail.FITMENT_DETAIL_ID
     *
     * @mbg.generated
     */
    public void setFitmentDetailId(Integer fitmentDetailId) {
        this.fitmentDetailId = fitmentDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_fitment_detail.IMG_URL
     *
     * @return the value of tt_fitment_detail.IMG_URL
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_fitment_detail.IMG_URL
     *
     * @param imgUrl the value for tt_fitment_detail.IMG_URL
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_fitment_detail.FITMENT_ID
     *
     * @return the value of tt_fitment_detail.FITMENT_ID
     *
     * @mbg.generated
     */
    public Long getFitmentId() {
        return fitmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_fitment_detail.FITMENT_ID
     *
     * @param fitmentId the value for tt_fitment_detail.FITMENT_ID
     *
     * @mbg.generated
     */
    public void setFitmentId(Long fitmentId) {
        this.fitmentId = fitmentId;
    }
}