package com.troytan.notify.domain;

import java.util.Date;

public class NotifyUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_notify_user.NOTIFY_ID
     *
     * @mbg.generated
     */
    private Integer notifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_notify_user.USER_ID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_notify_user.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_notify_user.NOTIFY_ID
     *
     * @return the value of tr_notify_user.NOTIFY_ID
     *
     * @mbg.generated
     */
    public Integer getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_notify_user.NOTIFY_ID
     *
     * @param notifyId the value for tr_notify_user.NOTIFY_ID
     *
     * @mbg.generated
     */
    public void setNotifyId(Integer notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_notify_user.USER_ID
     *
     * @return the value of tr_notify_user.USER_ID
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_notify_user.USER_ID
     *
     * @param userId the value for tr_notify_user.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_notify_user.CREATE_ON
     *
     * @return the value of tr_notify_user.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_notify_user.CREATE_ON
     *
     * @param createOn the value for tr_notify_user.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }
}