package com.troytan.notify.domain;

import java.util.Date;

public class NotifyImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify_image.NOTIFY_IMAGE_ID
     *
     * @mbg.generated
     */
    private Integer notifyImageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify_image.NOTIFY_ID
     *
     * @mbg.generated
     */
    private Integer notifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify_image.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify_image.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify_image.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify_image.NOTIFY_IMAGE_ID
     *
     * @return the value of tt_notify_image.NOTIFY_IMAGE_ID
     *
     * @mbg.generated
     */
    public Integer getNotifyImageId() {
        return notifyImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify_image.NOTIFY_IMAGE_ID
     *
     * @param notifyImageId the value for tt_notify_image.NOTIFY_IMAGE_ID
     *
     * @mbg.generated
     */
    public void setNotifyImageId(Integer notifyImageId) {
        this.notifyImageId = notifyImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify_image.NOTIFY_ID
     *
     * @return the value of tt_notify_image.NOTIFY_ID
     *
     * @mbg.generated
     */
    public Integer getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify_image.NOTIFY_ID
     *
     * @param notifyId the value for tt_notify_image.NOTIFY_ID
     *
     * @mbg.generated
     */
    public void setNotifyId(Integer notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify_image.URL
     *
     * @return the value of tt_notify_image.URL
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify_image.URL
     *
     * @param url the value for tt_notify_image.URL
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify_image.CREATE_BY
     *
     * @return the value of tt_notify_image.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify_image.CREATE_BY
     *
     * @param createBy the value for tt_notify_image.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify_image.CREATE_ON
     *
     * @return the value of tt_notify_image.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify_image.CREATE_ON
     *
     * @param createOn the value for tt_notify_image.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }
}