package com.troytan.notify.domain;

import java.util.Date;

public class Notify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.NOTIFY_ID
     *
     * @mbg.generated
     */
    private Integer notifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.STATUS
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.GROUP_ID
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_notify.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.NOTIFY_ID
     *
     * @return the value of tt_notify.NOTIFY_ID
     *
     * @mbg.generated
     */
    public Integer getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.NOTIFY_ID
     *
     * @param notifyId the value for tt_notify.NOTIFY_ID
     *
     * @mbg.generated
     */
    public void setNotifyId(Integer notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.TITLE
     *
     * @return the value of tt_notify.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.TITLE
     *
     * @param title the value for tt_notify.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.CONTENT
     *
     * @return the value of tt_notify.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.CONTENT
     *
     * @param content the value for tt_notify.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.NAME
     *
     * @return the value of tt_notify.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.NAME
     *
     * @param name the value for tt_notify.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.STATUS
     *
     * @return the value of tt_notify.STATUS
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.STATUS
     *
     * @param status the value for tt_notify.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.GROUP_ID
     *
     * @return the value of tt_notify.GROUP_ID
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.GROUP_ID
     *
     * @param groupId the value for tt_notify.GROUP_ID
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.CREATE_BY
     *
     * @return the value of tt_notify.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.CREATE_BY
     *
     * @param createBy the value for tt_notify.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.CREATE_ON
     *
     * @return the value of tt_notify.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.CREATE_ON
     *
     * @param createOn the value for tt_notify.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.UPDATE_BY
     *
     * @return the value of tt_notify.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.UPDATE_BY
     *
     * @param updateBy the value for tt_notify.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_notify.UPDATE_ON
     *
     * @return the value of tt_notify.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_notify.UPDATE_ON
     *
     * @param updateOn the value for tt_notify.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }
}