package com.troytan.notify.domain;

public class Worker {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_worker.WORKER_ID
     *
     * @mbg.generated
     */
    private Integer workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_worker.IMG_URL
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_worker.WORKER_ID
     *
     * @return the value of tt_worker.WORKER_ID
     *
     * @mbg.generated
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_worker.WORKER_ID
     *
     * @param workerId the value for tt_worker.WORKER_ID
     *
     * @mbg.generated
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_worker.IMG_URL
     *
     * @return the value of tt_worker.IMG_URL
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_worker.IMG_URL
     *
     * @param imgUrl the value for tt_worker.IMG_URL
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}