package com.troytan.notify.repository;

import com.troytan.notify.domain.Confirm;
import com.troytan.notify.dto.ConfirmDto;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ConfirmMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_confirm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer confirmId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_confirm
     *
     * @mbg.generated
     */
    int insert(Confirm record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_confirm
     *
     * @mbg.generated
     */
    Confirm selectByPrimaryKey(Integer confirmId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_confirm
     *
     * @mbg.generated
     */
    List<Confirm> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_confirm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Confirm record);

    void updateStatusByNotifyId(@Param("notifyId") Integer notifyId, @Param("status") short status,
                                @Param("userId") Integer userId);

    List<ConfirmDto> listConfirmByNotifyId(Integer notifyId);

    Confirm selectByUserAndNotify(@Param("userId") Integer userId, @Param("notifyId") Integer notifyId);
}
