package com.troytan.notify.repository;

import java.util.List;

import com.troytan.notify.domain.FitmentDetail;

public interface FitmentDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fitmentDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    int insert(FitmentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    FitmentDetail selectByPrimaryKey(Integer fitmentDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    List<FitmentDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FitmentDetail record);
}