package com.troytan.notify.repository;

import com.troytan.notify.domain.Form;
import com.troytan.notify.dto.FormDto;

import java.util.List;

public interface FormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_form
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_form
     *
     * @mbg.generated
     */
    int insert(Form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_form
     *
     * @mbg.generated
     */
    Form selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_form
     *
     * @mbg.generated
     */
    List<Form> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Form record);

    List<FormDto> listFormId();
}