package com.troytan.notify.repository;

import com.troytan.notify.domain.GroupUser;
import com.troytan.notify.dto.GroupUserDto;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("groupId") String groupId, @Param("openId") String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    int insert(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    GroupUser selectByPrimaryKey(@Param("groupId") String groupId, @Param("openId") String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    List<GroupUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupUser record);

    List<GroupUserDto> listGroupUsers(Integer userId);

    void updateBatch(List<GroupUserDto> groupUsers);
}