package com.troytan.notify.repository;

import com.troytan.notify.domain.NotifyImage;
import java.util.List;

public interface NotifyImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_notify_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer notifyImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_notify_image
     *
     * @mbg.generated
     */
    int insert(NotifyImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_notify_image
     *
     * @mbg.generated
     */
    NotifyImage selectByPrimaryKey(Integer notifyImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_notify_image
     *
     * @mbg.generated
     */
    List<NotifyImage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_notify_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NotifyImage record);

    void deleteByNotifyId(Integer notifyId);
}